# Slightly self serving, but putting a connection-detail-less version of our initial config into the main repository, both
# as a way to encourage community participation but also to act as a real use-case
database:
 poolsize: 15
 connectionTimeout: 3000
 idleTimeout: 600000
 maxLifetime: 7200000
 dirtysave: 
  period: 12000
  delay: 6000
drops:
 OakTwigT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Oak Twig
     lore:
     - Oak Twig T1
  base:
   min: 1
   max: 1
   chance: 0.5
 SpruceTwigT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 1
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Spruce Twig
     lore:
     - Spruce Twig T1
  base:
   min: 1
   max: 1
   chance: 0.5
 BirchTwigT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 2
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Birch Twig
     lore:
     - Birch Twig T1
  base:
   min: 1
   max: 1
   chance: 0.5
 JungleTwigT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 3
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Jungle Twig
     lore:
     - Jungle Twig T1
  base:
   min: 1
   max: 1
   chance: 0.5
 AcaciaTwigT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG_2
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Acacia Twig
     lore:
     - Acacia Twig T1
  base:
   min: 1
   max: 1
   chance: 0.5
 DarkOakTwigT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG_2
    amount: 1
    damage: 1
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Dark Oak Twig
     lore:
     - Dark Oak Twig T1
  base:
   min: 1
   max: 1
   chance: 0.5
 OakBarkT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Oak Bark
     lore:
     - Oak Bark T2
  base:
   min: 1
   max: 1
   chance: 0.25
 SpruceBarkT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 1
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Spruce Bark
     lore:
     - Spruce Bark T2
  base:
   min: 1
   max: 1
   chance: 0.25
 BirchBarkT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 2
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Birch Bark
     lore:
     - Birch Bark T2
  base:
   min: 1
   max: 1
   chance: 0.25
 JungleBarkT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 3
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Jungle Bark
     lore:
     - Jungle Bark T2
  base:
   min: 1
   max: 1
   chance: 0.25
 AcaciaBarkT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG_2
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Acacia Bark
     lore:
     - Acacia Bark T2
  base:
   min: 1
   max: 1
   chance: 0.25
 DarkOakBarkT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG_2
    amount: 1
    damage: 1
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Dark Oak Bark
     lore:
     - Dark Oak Bark T2
  base:
   min: 1
   max: 1
   chance: 0.25
 OakTrunkT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Oak Trunk
     lore:
     - Oak Trunk T3
  base:
   min: 1
   max: 1
   chance: 0.125
 SpruceTrunkT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 1
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Spruce Trunk
     lore:
     - Spruce Trunk T3
  base:
   min: 1
   max: 1
   chance: 0.125
 BirchTrunkT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 2
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Birch Trunk
     lore:
     - Birch Trunk T3
  base:
   min: 1
   max: 1
   chance: 0.125
 JungleTrunkT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 3
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Jungle Trunk
     lore:
     - Jungle Trunk T3
  base:
   min: 1
   max: 1
   chance: 0.125
 AcaciaTrunkT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG_2
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Acacia Trunk
     lore:
     - Acacia Trunk T3
  base:
   min: 1
   max: 1
   chance: 0.125
 DarkOakTrunkT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG_2
    amount: 1
    damage: 1
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Dark Oak Trunk
     lore:
     - Dark Oak Trunk T3
  base:
   min: 1
   max: 1
   chance: 0.125
 MixedTwigsT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: DEAD_BUSH
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Mixed Twigs
     lore:
     - Mixed Twigs T1
  base:
   min: 1
   max: 1
   chance: 0.5
 UncommonBarkT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: DEAD_BUSH
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Uncommon Bark
     lore:
     - Uncommon Bark T2
  base:
   min: 1
   max: 1
   chance: 0.25
 RareTrunkT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: DEAD_BUSH
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Rare Trunk
     lore:
     - Rare Trunk T3
  base:
   min: 1
   max: 1
   chance: 0.125
#CROPS
 BeetrootT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: BEETROOT
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Withered Beetroot
     lore:
     - Withered Beetroot T1
  base:
   min: 1
   max: 1
   chance: 0.5
 BeetrootT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: BEETROOT
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Average Beetroot
     lore:
     - Average Beetroot T2
  base:
   min: 1
   max: 1
   chance: 0.25
 BeetrootT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: BEETROOT
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Ripe Beetroot
     lore:
     - Ripe Beetroot T3
  base:
   min: 1
   max: 1
   chance: 0.125
 PumpkinT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: PUMPKIN
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Withered Pumpkin
     lore:
     - Withered Pumpkin T1
  base:
   min: 1
   max: 1
   chance: 0.5
 PumpkinT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: PUMPKIN
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Average Pumpkin
     lore:
     - Average Pumpkin T2
  base:
   min: 1
   max: 1
   chance: 0.25
 PumpkinT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: PUMPKIN
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Ripe Pumpkin
     lore:
     - Ripe Pumpkin T3
  base:
   min: 1
   max: 1
   chance: 0.125
 SugarCaneT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: SUGAR_CANE_BLOCK
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Withered Sugar Cane
     lore:
     - Withered Sugar Cane T1
  base:
   min: 1
   max: 1
   chance: 0.5
 SugarCaneT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: SUGAR_CANE_BLOCK
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Average Sugar Cane
     lore:
     - Average Sugar Cane T2
  base:
   min: 1
   max: 1
   chance: 0.25
 SugarCaneT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: SUGAR_CANE_BLOCK
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Ripe Sugar Cane
     lore:
     - Ripe Sugar Cane T3
  base:
   min: 1
   max: 1
   chance: 0.125
 PotatoT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: POTATO
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Withered Potato
     lore:
     - Withered Potato T1
  base:
   min: 1
   max: 1
   chance: 0.5
 PotatoT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: POTATO
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Average Potato
     lore:
     - Average Potato T2
  base:
   min: 1
   max: 1
   chance: 0.25
 PotatoT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: POTATO
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Ripe Potato
     lore:
     - Ripe Potato T3
  base:
   min: 1
   max: 1
   chance: 0.125
 CarrotT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: CARROT
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Withered Carrot
     lore:
     - Withered Carrot T1
  base:
   min: 1
   max: 1
   chance: 0.5
 CarrotT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: CARROT
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Average Carrot
     lore:
     - Average Carrot T2
  base:
   min: 1
   max: 1
   chance: 0.25
 CarrotT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: CARROT
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Ripe Carrot
     lore:
     - Ripe Carrot T3
  base:
   min: 1
   max: 1
   chance: 0.125
 CocoaBeanT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: INK_SACK
    amount: 1
    damage: 3
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Withered Cocoa Bean
     lore:
     - Withered Cocoa Bean T1
  base:
   min: 1
   max: 1
   chance: 0.5
 CocoaBeanT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: INK_SACK
    amount: 1
    damage: 3
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Average Cocoa Bean
     lore:
     - Average Cocoa Bean T2
  base:
   min: 1
   max: 1
   chance: 0.25
 CocoaBeanT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: INK_SACK
    amount: 1
    damage: 3
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Ripe Cocoa Bean
     lore:
     - Ripe Cocoa Bean T3
  base:
   min: 1
   max: 1
   chance: 0.125
 CactusT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: CACTUS
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Withered Cactus
     lore:
     - Withered Cactus T1
  base:
   min: 1
   max: 1
   chance: 0.5
 CactusT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: CACTUS
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Average Cactus
     lore:
     - Average Cactus T2
  base:
   min: 1
   max: 1
   chance: 0.25
 CactusT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: CACTUS
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Ripe Cactus
     lore:
     - Ripe Cactus T3
  base:
   min: 1
   max: 1
   chance: 0.125
trees:
 TREE:
  drops:
   OakTwigT1:
    player:
     different:
      chance: 1.1
   OakBarkT2:
    player:
     different:
      chance: 1.1
   OakTrunkT3:
    player:
     different:
      chance: 1.1
   MixedTwigsT1:
    player:
     different:
      chance: 1.1
   UncommonBarkT2:
    player:
     different:
      chance: 1.1
   RareTrunkT3:
    player:
     different:
      chance: 1.1
 BIG_TREE:
  drops:
   OakTwigT1:
    player:
     different:
      chance: 1.1
   OakBarkT2:
    player:
     different:
      chance: 1.1
   OakTrunkT3:
    player:
     different:
      chance: 1.1
 REDWOOD:
  drops:
   SpruceTwigT1:
    player:
     different:
      chance: 1.1
   SpruceBarkT2:
    player:
     different:
      chance: 1.1
   SpruceTrunkT3:
    player:
     different:
      chance: 1.1
   MixedTwigsT1:
    player:
     different:
      chance: 1.1
   UncommonBarkT2:
    player:
     different:
      chance: 1.1
   RareTrunkT3:
    player:
     different:
      chance: 1.1
 TALL_REDWOOD:
  drops:
   SpruceTwigT1:
    player:
     different:
      chance: 1.1
   SpruceBarkT2:
    player:
     different:
      chance: 1.1
   SpruceTrunkT3:
    player:
     different:
      chance: 1.1
 BIRCH:
  drops:
   BirchTwigT1:
    player:
     different:
      chance: 1.1
   BirchBarkT2:
    player:
     different:
      chance: 1.1
   BirchTrunkT3:
    player:
     different:
      chance: 1.1
   MixedTwigsT1:
    player:
     different:
      chance: 1.1
   UncommonBarkT2:
    player:
     different:
      chance: 1.1
   RareTrunkT3:
    player:
     different:
      chance: 1.1
 JUNGLE:
  drops:
   JungleTwigT1:
    player:
     different:
      chance: 1.1
   JungleBarkT2:
    player:
     different:
      chance: 1.1
   JungleTrunkT3:
    player:
     different:
      chance: 1.1
 SMALL_JUNGLE:
  drops:
   JungleTwigT1:
    player:
     different:
      chance: 1.1
   JungleBarkT2:
    player:
     different:
      chance: 1.1
   JungleTrunkT3:
    player:
     different:
      chance: 1.1
   MixedTwigsT1:
    player:
     different:
      chance: 1.1
   UncommonBarkT2:
    player:
     different:
      chance: 1.1
   RareTrunkT3:
    player:
     different:
      chance: 1.1
 COCOA_TREE:
  drops:
   JungleTwigT1:
    player:
     different:
      chance: 1.1
   JungleBarkT2:
    player:
     different:
      chance: 1.1
   JungleTrunkT3:
    player:
     different:
      chance: 1.1
 JUNGLE_BUSH:
  drops:
   JungleTwigT1:
    player:
     different:
      chance: 1.1
   JungleBarkT2:
    player:
     different:
      chance: 1.1
   JungleTrunkT3:
    player:
     different:
      chance: 1.1
 SWAMP:
  drops:
   OakTwigT1:
    player:
     different:
      chance: 1.1
   OakBarkT2:
    player:
     different:
      chance: 1.1
   OakTrunkT3:
    player:
     different:
      chance: 1.1
 ACACIA:
  drops:
   AcaciaTwigT1:
    player:
     different:
      chance: 1.1
   AcaciaBarkT2:
    player:
     different:
      chance: 1.1
   AcaciaTrunkT3:
    player:
     different:
      chance: 1.1
   MixedTwigsT1:
    player:
     different:
      chance: 1.1
   UncommonBarkT2:
    player:
     different:
      chance: 1.1
   RareTrunkT3:
    player:
     different:
      chance: 1.1
 DARK_OAK:
  drops:
   DarkOakTwigT1:
    player:
     different:
      chance: 1.1
   DarkOakBarkT2:
    player:
     different:
      chance: 1.1
   DarkOakTrunkT3:
    player:
     different:
      chance: 1.1
 MEGA_REDWOOD:
  drops:
   SpruceTwigT1:
    player:
     different:
      chance: 1.1
   SpruceBarkT2:
    player:
     different:
      chance: 1.1
   SpruceTrunkT3:
    player:
     different:
      chance: 1.1
 TALL_BIRCH:
  drops:
   BirchTwigT1:
    player:
     different:
      chance: 1.1
   BirchBarkT2:
    player:
     different:
      chance: 1.1
   BirchTrunkT3:
    player:
     different:
      chance: 1.1
# Speculative Sections for advanced testing
crops:
 CARROT: 
  RIPE:
   drops:
    CarrotT1:
     player:
      different:
       chance: 1.1
    CarrotT2:
     player:
      different:
       chance: 1.1
    CarrotT3:
     player:
      different:
       chance: 1.1
 COCOA:
  LARGE:
   drops:
    CocoaBeanT1:
     player:
      different:
       chance: 1.1
    CocoaBeanT2:
     player:
      different:
       chance: 1.1
    CocoaBeanT3:
     player:
      different:
       chance: 1.1
 POTATO:
  RIPE:
   drops:
    PotatoT1:
     player:
      different:
       chance: 1.1
    PotatoT2:
     player:
      different:
       chance: 1.1
    PotatoT3:
     player:
      different:
       chance: 1.1
 PUMPKIN:
  drops:
   PumpkinT1:
    player:
     different:
      chance: 1.1
   PumpkinT2:
    player:
     different:
      chance: 1.1
   PumpkinT3:
    player:
     different:
      chance: 1.1
 SUGAR_CANE_BLOCK:
  drops:
   SugarCaneT1:
    player:
     different:
      chance: 1.1
   SugarCaneT2:
    player:
     different:
      chance: 1.1
   SugarCaneT3:
    player:
     different:
      chance: 1.1
 BEETROOT_BLOCK:
  RIPE:
   drops:
    BeetrootT1:
     player:
      different:
       chance: 1.1
    BeetrootT2:
     player:
      different:
       chance: 1.1
    BeetrootT3:
     player:
      different:
       chance: 1.1
 CACTUS:
  drops:
   CactusT1:
    player:
     different:
      chance: 1.1
   CactusT2:
    player:
     different:
      chance: 1.1
   CactusT3:
    player:
     different:
      chance: 1.1