# Slightly self serving, but putting a connection-detail-less version of our initial config into the main repository, both
# as a way to encourage community participation but also to act as a real use-case
database:
 poolsize: 15
 connectionTimeout: 3000
 idleTimeout: 600000
 maxLifetime: 7200000
 dirtysave: 
  period: 12000
  delay: 6000
drops:
 OakTwigT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Oak Twig
     lore:
     - Oak Twig T1
  base:
   min: 1
   max: 1
   chance: 0.5
 SpruceTwigT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 1
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Spruce Twig
     lore:
     - Spruce Twig T1
  base:
   min: 1
   max: 1
   chance: 0.5
 BirchTwigT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 2
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Birch Twig
     lore:
     - Birch Twig T1
  base:
   min: 1
   max: 1
   chance: 0.5
 JungleTwigT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 3
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Jungle Twig
     lore:
     - Jungle Twig T1
  base:
   min: 1
   max: 1
   chance: 0.5
 AcaciaTwigT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG_2
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Acacia Twig
     lore:
     - Acacia Twig T1
  base:
   min: 1
   max: 1
   chance: 0.5
 DarkOakTwigT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG_2
    amount: 1
    damage: 1
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Dark Oak Twig
     lore:
     - Dark Oak Twig T1
  base:
   min: 1
   max: 1
   chance: 0.5
 OakBarkT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Oak Bark
     lore:
     - Oak Bark T2
  base:
   min: 1
   max: 1
   chance: 0.25
 SpruceBarkT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 1
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Spruce Bark
     lore:
     - Spruce Bark T2
  base:
   min: 1
   max: 1
   chance: 0.25
 BirchBarkT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 2
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Birch Bark
     lore:
     - Birch Bark T2
  base:
   min: 1
   max: 1
   chance: 0.25
 JungleBarkT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 3
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Jungle Bark
     lore:
     - Jungle Bark T2
  base:
   min: 1
   max: 1
   chance: 0.25
 AcaciaBarkT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG_2
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Acacia Bark
     lore:
     - Acacia Bark T2
  base:
   min: 1
   max: 1
   chance: 0.25
 DarkOakBarkT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG_2
    amount: 1
    damage: 1
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Dark Oak Bark
     lore:
     - Dark Oak Bark T2
  base:
   min: 1
   max: 1
   chance: 0.25
 OakTrunkT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Oak Trunk
     lore:
     - Oak Trunk T3
  base:
   min: 1
   max: 1
   chance: 0.125
 SpruceTrunkT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 1
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Spruce Trunk
     lore:
     - Spruce Trunk T3
  base:
   min: 1
   max: 1
   chance: 0.125
 BirchTrunkT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 2
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Birch Trunk
     lore:
     - Birch Trunk T3
  base:
   min: 1
   max: 1
   chance: 0.125
 JungleTrunkT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG
    amount: 1
    damage: 3
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Jungle Trunk
     lore:
     - Jungle Trunk T3
  base:
   min: 1
   max: 1
   chance: 0.125
 AcaciaTrunkT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG_2
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Acacia Trunk
     lore:
     - Acacia Trunk T3
  base:
   min: 1
   max: 1
   chance: 0.125
 DarkOakTrunkT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: LOG_2
    amount: 1
    damage: 1
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Dark Oak Trunk
     lore:
     - Dark Oak Trunk T3
  base:
   min: 1
   max: 1
   chance: 0.125
 MixedTwigsT1:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: DEAD_BUSH
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Mixed Twigs
     lore:
     - Mixed Twigs T1
  base:
   min: 1
   max: 1
   chance: 0.5
 UncommonBarkT2:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: DEAD_BUSH
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Uncommon Bark
     lore:
     - Uncommon Bark T2
  base:
   min: 1
   max: 1
   chance: 0.25
 RareTrunkT3:
  template:
  - ==: org.bukkit.inventory.ItemStack
    type: DEAD_BUSH
    amount: 1
    damage: 0
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Rare Trunk
     lore:
     - Rare Trunk T3
  base:
   min: 1
   max: 1
   chance: 0.125
 TestingPlaceholder:
  template:
  - ==: org.bukkt.inventory.ItemStack
    type: DIRT
    amount: 2
    meta:
     ==: ItemMeta
     meta-type: UNSPECIFIC
     display-name: Rare Testing Object
  base:
   min: 1
   max: 5
   chance: 0.05
trees:
 TREE:
  drops:
   OakTwigT1:
    player:
     same: 1.1
   OakBarkT2:
    player:
     same: 1.1
   OakTrunkT3:
    player:
     same: 1.1
   MixedTwigsT1:
    player:
     same: 1.1
    chance: 0.0001
    biomes:
     FOREST:
      chance: 100.0
   UncommonBarkT2:
    player:
     same: 1.1
    chance: 0.0001
    biomes:
     FOREST:
      chance: 100.0
   RareTrunkT3:
    player:
     same: 1.1
    chance: 0.0001
    biomes:
     FOREST:
      chance: 100.0
 BIG_TREE:
  drops:
   OakTwigT1:
    player:
     same: 1.1
   OakBarkT2:
    player:
     same: 1.1
   OakTrunkT3:
    player:
     same: 1.1
 REDWOOD:
  drops:
   SpruceTwigT1:
    player:
     same: 1.1
   SpruceBarkT2:
    player:
     same: 1.1
   SpruceTrunkT3:
    player:
     same: 1.1
 TALL_REDWOOD:
  drops:
   SpruceTwigT1:
    player:
     same: 1.1
   SpruceBarkT2:
    player:
     same: 1.1
   SpruceTrunkT3:
    player:
     same: 1.1
 BIRCH:
  drops:
   BirchTwigT1:
    player:
     same: 1.1
   BirchBarkT2:
    player:
     same: 1.1
   BirchTrunkT3:
    player:
     same: 1.1
 JUNGLE:
  drops:
   JungleTwigT1:
    player:
     same: 1.1
   JungleBarkT2:
    player:
     same: 1.1
   JungleTrunkT3:
    player:
     same: 1.1
 SMALL_JUNGLE:
  drops:
   JungleTwigT1:
    player:
     same: 1.1
   JungleBarkT2:
    player:
     same: 1.1
   JungleTrunkT3:
    player:
     same: 1.1
 COCOA_TREE:
  drops:
   JungleTwigT1:
    player:
     same: 1.1
   JungleBarkT2:
    player:
     same: 1.1
   JungleTrunkT3:
    player:
     same: 1.1
 JUNGLE_BUSH:
  drops:
   JungleTwigT1:
    player:
     same: 1.1
   JungleBarkT2:
    player:
     same: 1.1
   JungleTrunkT3:
    player:
     same: 1.1
 SWAMP:
  drops:
   OakTwigT1:
    player:
     same: 1.1
   OakBarkT2:
    player:
     same: 1.1
   OakTrunkT3:
    player:
     same: 1.1
 ACACIA:
  drops:
   AcaciaTwigT1:
    player:
     same: 1.1
   AcaciaBarkT2:
    player:
     same: 1.1
   AcaciaTrunkT3:
    player:
     same: 1.1
 DARK_OAK:
  drops:
   DarkOakTwigT1:
    player:
     same: 1.1
   DarkOakBarkT2:
    player:
     same: 1.1
   DarkOakTrunkT3:
    player:
     same: 1.1
 MEGA_REDWOOD:
  drops:
   SpruceTwigT1:
    player:
     same: 1.1
   SpruceBarkT2:
    player:
     same: 1.1
   SpruceTrunkT3:
    player:
     same: 1.1
 TALL_BIRCH:
  drops:
   BirchTwigT1:
    player:
     same: 1.1
   BirchBarkT2:
    player:
     same: 1.1
   BirchTrunkT3:
    player:
     same: 1.1

