name: ${project.name}
version: ${project.version}
authors: [ProgrammerDan, xFier]
depend: [CivModCore]
main: com.programmerdan.minecraft.cropcontrol.CropControl
description: Fills the gaps left by RealisticBiomes and HiddenOre; control drops for player-grown plants and trees
