name: ${project.name}
version: ${project.version}
authors: [ProgrammerDan, xFier]
depend: [CivModCore]
softdepend: [RealisticBiomes]
main: com.programmerdan.minecraft.cropcontrol.CropControl
description: Fills the gaps left by RealisticBiomes and HiddenOre; augment drops for player-grown plants and trees
commands:
   cropcontrol:
      description: CropControl allows the augment of plant and tree drops. This reloads the config.
      usage: /cropcontrol
      permission: cropcontrol.adv
permissions:
    cropcontrol.*:
      description: Gives access to all CropControl commands
      default: op
      children:
        cropcontrol.adv: true
        cropcontrol.debug: true
    cropcontrol.adv:
      description: Allows access to  CropControl commands.
      default: op
    cropcontrol.debug:
      description: Enables the CropControl debug interface.
      default: op
